//CRUD

//Crecion Base de Datos
use("Colegio");

//Creacion coleccion Biblioteca
// db.createCollection("Biblioteca");

//Insertando un dato
// db.Biblioteca.insertOne({
//    titulo: "El Viaje Eterno",
// editorial: "Libros Universales",
// publicacion: 2020,
// paginas: 300,
// idiomas: ["Espanol", "Ingles"],
// });

//Insert Many
db.Biblioteca.insertMany([
  {
    titulo: "El Viaje Eterno",
    editorial: "Libros Universales",
    publicacion: 2020,
    paginas: 300,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Le Monde Magique",
    editorial: "Editions de Paris",
    publicacion: 2021,
    paginas: 280,
    idiomas: ["Espanol", "Frances"],
  },
  {
    titulo: "La Ultima Aventura",
    editorial: "Editorial Fantastica",
    publicacion: 2019,
    paginas: 255,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Voyage dans le Temps",
    editorial: "Editions de Lyon",
    publicacion: 2023,
    paginas: 320,
    idiomas: ["Espanol", "Frances"],
  },
  {
    titulo: "El Enigma",
    editorial: "Misterio Editorial",
    publicacion: 2022,
    paginas: 210,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Riddles and Puzzles",
    editorial: "Puzzle Press",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Aventuras en el Espacio",
    editorial: "Galaxy Books",
    publicacion: 2021,
    paginas: 350,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Mysteres de Paris",
    editorial: "Librairie Francaise",
    publicacion: 2019,
    paginas: 240,
    idiomas: ["Espanol", "Frances"],
  },
  {
    titulo: "The Time Traveler's Guide",
    editorial: "Chronicle Publishing",
    publicacion: 2023,
    paginas: 300,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Historias de Fantasmas",
    editorial: "Editorial de Terror",
    publicacion: 2022,
    paginas: 275,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Mysteries of the Unknown",
    editorial: "Enigma Press",
    publicacion: 2020,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Aventuras en el Amazonas",
    editorial: "Selva Libros",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol", "Portugues"],
  },
  {
    titulo: "Les Contes Magiques",
    editorial: "Contes de Fees",
    publicacion: 2018,
    paginas: 260,
    idiomas: ["Espanol", "Frances"],
  },
  {
    titulo: "The Mysterious Mansion",
    editorial: "Mansion Books",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Aventuras en el Desierto",
    editorial: "Arena Editorial",
    publicacion: 2019,
    paginas: 245,
    idiomas: ["Espanol", "Arabe"],
  },
  {
    titulo: "La Foret Enchantee",
    editorial: "Foret Editions",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Espanol", "Frances"],
  },
  {
    titulo: "The Haunted Castle",
    editorial: "Castle Books",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Viaje al Futuro",
    editorial: "Futuristic Press",
    publicacion: 2023,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Egypte Ancienne",
    editorial: "Pharaon Editions",
    publicacion: 2022,
    paginas: 300,
    idiomas: ["Espanol", "Frances"],
  },
  {
    titulo: "The Lost City",
    editorial: "Explorer Publishing",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Aventuras en la Selva Amazonica",
    editorial: "Amazon Jungle",
    publicacion: 2021,
    paginas: 310,
    idiomas: ["Espanol", "Portugues"],
  },
  //   21 DATOS
  {
    titulo: "El Castillo Encantado",
    editorial: "Libros Fantasticos",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "L'Enigme de la Tour",
    editorial: "Editions Mystere",
    publicacion: 2021,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Forbidden Forest",
    editorial: "Enchanted Tales",
    publicacion: 2020,
    paginas: 290,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Misterios del Pasado",
    editorial: "Editorial Historica",
    publicacion: 2022,
    paginas: 270,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Voyage au Centre de la Terre",
    editorial: "Editions Parisienne",
    publicacion: 2019,
    paginas: 310,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunting of Hill House",
    editorial: "Horror Publications",
    publicacion: 2021,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en el Lejano Oeste",
    editorial: "Western Books",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de la Nature",
    editorial: "Editions Naturelles",
    publicacion: 2023,
    paginas: 290,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Lost Treasure",
    editorial: "Treasure Hunter Publishing",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Hechizos",
    editorial: "Magia Antigua",
    publicacion: 2022,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Mystere de la Pyramide",
    editorial: "Editions Pharaon",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Phantom Ship",
    editorial: "Maritime Mysteries",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Secreto del Alquimista",
    editorial: "Alquimia Ediciones",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Grimm",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Garden",
    editorial: "Garden Publishing",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Tesoro de la Isla Perdida",
    editorial: "Aventuras Marinas",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de la Lune",
    editorial: "Editions Lunaire",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Witch's Curse",
    editorial: "Witchcraft Press",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en el Mundo Subterraneo",
    editorial: "Subterranean Books",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Mysteres",
    editorial: "Chateau Editions",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  //   41 DATOS
  {
    titulo: "El Misterio del Faro",
    editorial: "Libros de Misterio",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de la Foret",
    editorial: "Editions Naturelles",
    publicacion: 2021,
    paginas: 270,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ghostly Manor",
    editorial: "Haunted House Publications",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Relatos Historicos",
    editorial: "Historias Antiguas",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Espanol"],
  },
  {
    titulo: "La Quete du Tresor Perdu",
    editorial: "Editions Aventures",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Witching Hour",
    editorial: "Witchcraft & Spells",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en el Espacio Profundo",
    editorial: "Galactic Adventures",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Enquetes de Detective",
    editorial: "Editions Detective",
    publicacion: 2023,
    paginas: 290,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Lost Civilization",
    editorial: "Ancient Mysteries",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Grimorio de las Sombras",
    editorial: "Magia Oscura",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Aventures de l'Explorateur",
    editorial: "Editions Aventure",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Cursed Amulet",
    editorial: "Curse Breaker Publishing",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro Prohibido",
    editorial: "Magia Antigua",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Fees",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Forest",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de las Maravillas",
    editorial: "Aventuras Fantasticas",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Ocean",
    editorial: "Editions Oceanique",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Woods",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Tierra de los Dragones",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  //   61 DATOS
  {
    titulo: "El Tesoro de los Piratas",
    editorial: "Aventuras Marinas",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Mysteries of the Ancient World",
    editorial: "Historical Explorations",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "La Leyenda del Caballero Negro",
    editorial: "Libros de Leyendas",
    publicacion: 2020,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Voyage to the Unknown",
    editorial: "Adventure Journeys",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets de la Ville Fantôme",
    editorial: "Éditions Mystérieuses",
    publicacion: 2021,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2018,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Enigma de la Esfinge",
    editorial: "Misterios Antiguos",
    publicacion: 2023,
    paginas: 300,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Aventuras en la Época Victoriana",
    editorial: "Victorian Adventures",
    publicacion: 2017,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Lost Scrolls",
    editorial: "Scroll Discoveries",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Mystères de la Renaissance",
    editorial: "Éditions Artistiques",
    publicacion: 2021,
    paginas: 310,
    idiomas: ["Frances"],
  },
  {
    titulo: "El Libro de las Profecías",
    editorial: "Profecías Antiguas",
    publicacion: 2019,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Voyage to the Underworld",
    editorial: "Underworld Expeditions",
    publicacion: 2023,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets de l'Alchimiste",
    editorial: "Éditions Alchimie",
    publicacion: 2018,
    paginas: 270,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Mansion",
    editorial: "Spooky House Publishing",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Enigma de Stonehenge",
    editorial: "Misterios Antiguos",
    publicacion: 2021,
    paginas: 280,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Aventuras en la China Antigua",
    editorial: "Chinese Adventures",
    publicacion: 2020,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Mystères de l'Égypte Ancienne",
    editorial: "Éditions Égyptiennes",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Lost City of Atlantis",
    editorial: "Atlantean Discoveries",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Enigma de las Piramides",
    editorial: "Misterios Antiguos",
    publicacion: 2018,
    paginas: 270,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Voyage to the Stars",
    editorial: "Stellar Journeys",
    publicacion: 2023,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  //   81 DATOS
  {
    titulo: "El Misterio del Valle Prohibido",
    editorial: "Libros de Misterio",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Lost Civilizations of the Amazon",
    editorial: "Explorer's Press",
    publicacion: 2021,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "La Légende du Chevalier Sans Peur",
    editorial: "Contes Médiévaux",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Frances"],
  },
  {
    titulo: "Voyage to the Center of the Earth",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets de la Forêt Enchantée",
    editorial: "Éditions Magiques",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Curse of the Pharaohs",
    editorial: "Ancient Secrets",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Época de los Piratas",
    editorial: "Pirate Tales",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Enquêtes de Sherlock Holmes",
    editorial: "Éditions Mystère",
    publicacion: 2023,
    paginas: 290,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ancient Wonders of the World",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de las Sombras",
    editorial: "Magia Antigua",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Voyages de Marco Polo",
    editorial: "Éditions Aventure",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Mysterious Caves",
    editorial: "Cave Exploration",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Secreto de las Brujas",
    editorial: "Magia y Hechicería",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Grimm",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Garden",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas",
    editorial: "Aventuras Fantasticas",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Océan Profond",
    editorial: "Éditions Sous-marines",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Woods",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Tierra de los Dragones",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  //   101 DATOS
  {
    titulo: "El Misterio del Faro Encantado",
    editorial: "Libros de Misterio",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Lost Legends of Camelot",
    editorial: "Medieval Tales",
    publicacion: 2021,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "La Légende du Roi Arthur",
    editorial: "Contes Médiévaux",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Frances"],
  },
  {
    titulo: "Voyage to the Stars",
    editorial: "Stellar Journeys",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets de la Cité Perdue",
    editorial: "Éditions Aventures",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ghost Ship",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en el Lejano Oeste",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Enquêtes de Sherlock Holmes",
    editorial: "Éditions Mystère",
    publicacion: 2023,
    paginas: 290,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Quest for the Holy Grail",
    editorial: "Legendary Quests",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Dragones",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Voyages de Jules Verne",
    editorial: "Éditions Aventure",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Secreto de las Brujas",
    editorial: "Magia y Hechicería",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Grimm",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Forest",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas",
    editorial: "Aventuras Fantasticas",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Océan Profond",
    editorial: "Éditions Sous-marines",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Woods",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Tierra de los Dragones",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  // 121 DATOS
  {
    titulo: "El Secreto de la Montaña Encantada",
    editorial: "Libros de Misterio",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Lost Treasures of the Mayans",
    editorial: "Explorer's Press",
    publicacion: 2021,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "La Quête du Graal",
    editorial: "Contes Médiévaux",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Frances"],
  },
  {
    titulo: "Voyage to the Unknown",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets de la Vallée Perdue",
    editorial: "Éditions Aventures",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ghostly Shipwrecks",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en el Salvaje Oeste",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Enquêtes de Sherlock Holmes",
    editorial: "Éditions Mystère",
    publicacion: 2023,
    paginas: 290,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ancient Civilizations",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Dragones",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Voyages de Jules Verne",
    editorial: "Éditions Aventure",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Secreto de las Brujas",
    editorial: "Magia y Hechicería",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Grimm",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Forest",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas",
    editorial: "Aventuras Fantasticas",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Océan Profond",
    editorial: "Éditions Sous-marines",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Woods",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Tierra de los Dragones",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  // 141 DATOS
  {
    titulo: "El Enigma del Castillo de Piedra",
    editorial: "Libros de Misterio",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Lost Cities of Atlantis",
    editorial: "Explorer's Press",
    publicacion: 2021,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "La Quête de l'Arche Perdue",
    editorial: "Contes Médiévaux",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Frances"],
  },
  {
    titulo: "Voyage to the Underworld",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets de la Montagne Sacrée",
    editorial: "Éditions Aventures",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ghostly Shipwrecks",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en el Lejano Oeste",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Enquêtes de Sherlock Holmes",
    editorial: "Éditions Mystère",
    publicacion: 2023,
    paginas: 290,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ancient Civilizations",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Dragones",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Voyages de Jules Verne",
    editorial: "Éditions Aventure",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Secreto de las Brujas",
    editorial: "Magia y Hechicería",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Grimm",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Forest",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas",
    editorial: "Aventuras Fantasticas",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Océan Profond",
    editorial: "Éditions Sous-marines",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Woods",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Tierra de los Dragones",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  // 161 DATOS
  {
    titulo: "El Misterio del Valle Prohibido",
    editorial: "Libros de Misterio",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Lost Worlds of the Incas",
    editorial: "Explorer's Press",
    publicacion: 2021,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "La Quête de l'Idole d'Or",
    editorial: "Contes Médiévaux",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Frances"],
  },
  {
    titulo: "Voyage to the Forgotten Realms",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets du Temple Perdu",
    editorial: "Éditions Aventures",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ghostly Shipwrecks",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en el Salvaje Oeste",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Enquêtes de Sherlock Holmes",
    editorial: "Éditions Mystère",
    publicacion: 2023,
    paginas: 290,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ancient Civilizations",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Dragones",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Voyages de Jules Verne",
    editorial: "Éditions Aventure",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Secreto de las Brujas",
    editorial: "Magia y Hechicería",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Grimm",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Forest",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas",
    editorial: "Aventuras Fantasticas",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Océan Profond",
    editorial: "Éditions Sous-marines",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Woods",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Tierra de los Dragones",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  // 181 DATOS
  {
    titulo: "El Tesoro de los Piratas",
    editorial: "Libros de Aventuras",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Ancient Riddles and Mysteries",
    editorial: "Explorer's Press",
    publicacion: 2021,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "La Quête de l'Épée Magique",
    editorial: "Contes Médiévaux",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Frances"],
  },
  {
    titulo: "Voyage to the Underworld",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets de la Montagne Sacrée",
    editorial: "Éditions Aventures",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ghostly Shipwrecks",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en el Salvaje Oeste",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Enquêtes de Sherlock Holmes",
    editorial: "Éditions Mystère",
    publicacion: 2023,
    paginas: 290,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ancient Civilizations",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Dragones",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Voyages de Jules Verne",
    editorial: "Éditions Aventure",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Secreto de las Brujas",
    editorial: "Magia y Hechicería",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Grimm",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Forest",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas",
    editorial: "Aventuras Fantasticas",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Océan Profond",
    editorial: "Éditions Sous-marines",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Woods",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Tierra de los Dragones",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  //   201 DATOS
  {
    titulo: "El Misterio del Valle de los Dinosaurios",
    editorial: "Libros de Aventuras",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Lost Worlds of the Maya",
    editorial: "Explorer's Press",
    publicacion: 2021,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "La Quête de l'Amulette Magique",
    editorial: "Contes Médiévaux",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Frances"],
  },
  {
    titulo: "Voyage to the Forgotten Realms",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets du Temple Perdu",
    editorial: "Éditions Aventures",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ghostly Shipwrecks",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en el Salvaje Oeste",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Enquêtes de Sherlock Holmes",
    editorial: "Éditions Mystère",
    publicacion: 2023,
    paginas: 290,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ancient Civilizations",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Dragones",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Voyages de Jules Verne",
    editorial: "Éditions Aventure",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Secreto de las Brujas",
    editorial: "Magia y Hechicería",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Grimm",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Forest",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas",
    editorial: "Aventuras Fantasticas",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Océan Profond",
    editorial: "Éditions Sous-marines",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Woods",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Tierra de los Dragones",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  // 221 DATOS
  {
    titulo: "El Misterio del Templo Maya",
    editorial: "Libros de Aventuras",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Lost Worlds of Atlantis",
    editorial: "Explorer's Press",
    publicacion: 2021,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "La Quête de la Pierre Sacrée",
    editorial: "Contes Médiévaux",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Frances"],
  },
  {
    titulo: "Voyage to the Underworld",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets de la Cité Perdue",
    editorial: "Éditions Aventures",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ghostly Shipwrecks",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en el Salvaje Oeste",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Enquêtes de Sherlock Holmes",
    editorial: "Éditions Mystère",
    publicacion: 2023,
    paginas: 290,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ancient Civilizations",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Dragones",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Voyages de Jules Verne",
    editorial: "Éditions Aventure",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Secreto de las Brujas",
    editorial: "Magia y Hechicería",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Grimm",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Forest",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas",
    editorial: "Aventuras Fantasticas",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Océan Profond",
    editorial: "Éditions Sous-marines",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Woods",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Tierra de los Dragones",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  //   241 DATOS
  {
    titulo: "El Misterio del Faraon",
    editorial: "Libros de Misterio",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Lost Worlds of the Incas",
    editorial: "Explorer's Press",
    publicacion: 2021,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "La Quete du Tresor Enchante",
    editorial: "Contes Medievaux",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Frances"],
  },
  {
    titulo: "Voyage to the Forgotten Realms",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets du Royaume Perdu",
    editorial: "Editions Aventures",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ghostly Shipwrecks",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en el Salvaje Oeste",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Enquetes de Detective",
    editorial: "Editions Mystere",
    publicacion: 2023,
    paginas: 290,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Ancient Civilizations",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Dragones",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Voyages de Jules Verne",
    editorial: "Editions Aventure",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Secreto de las Brujas",
    editorial: "Magia y Hechiceria",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Grimm",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Forest",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas",
    editorial: "Aventuras Fantasticas",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Ocean Profond",
    editorial: "Editions Sous-marines",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Woods",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Tierra de los Dragones",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  //   261 DATOS
  {
    titulo: "El Misterio del Laberinto",
    editorial: "Libros de Enigma",
    publicacion: 2022,
    paginas: 295,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Ancient Riddles and Legends",
    editorial: "Historical Mysteries",
    publicacion: 2021,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "La Legende de l'Epee Magique",
    editorial: "Contes Fantastiques",
    publicacion: 2020,
    paginas: 315,
    idiomas: ["Frances"],
  },
  {
    titulo: "Realm of Wizards and Dragons",
    editorial: "Fantasy Realms",
    publicacion: 2022,
    paginas: 285,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets du Royaume Perdu",
    editorial: "Editions Aventures",
    publicacion: 2019,
    paginas: 305,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Underwater World",
    editorial: "Oceanic Adventures",
    publicacion: 2021,
    paginas: 325,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Travesias por el Viejo Oeste",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 335,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Enquetes du Detective Williams",
    editorial: "Editions Mystere",
    publicacion: 2023,
    paginas: 295,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Secrets of Ancient Egypt",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 275,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de las Criaturas Magicas",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 315,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Voyages de l'Explorateur Solitaire",
    editorial: "Editions Aventure",
    publicacion: 2018,
    paginas: 255,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 285,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Arte de la Magia",
    editorial: "Magia y Hechiceria",
    publicacion: 2021,
    paginas: 295,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Fees du Monde",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 265,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Garden of Wonders",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 315,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas Misteriosos",
    editorial: "Aventuras Fantasticas",
    publicacion: 2018,
    paginas: 295,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Ocean Inexplore",
    editorial: "Editions Sous-marines",
    publicacion: 2022,
    paginas: 285,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Forest",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 275,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Tierra de los Dragones Miticos",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 325,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres Enigmatiques",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 305,
    idiomas: ["Frances"],
  },
  // 281 DATOS
  {
    titulo: "El Misterio del Laberinto",
    editorial: "Libros de Enigma",
    publicacion: 2022,
    paginas: 295,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Ancient Riddles and Legends",
    editorial: "Historical Mysteries",
    publicacion: 2021,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "La Legende de l'Epee Magique",
    editorial: "Contes Fantastiques",
    publicacion: 2020,
    paginas: 315,
    idiomas: ["Frances"],
  },
  {
    titulo: "Realm of Wizards and Dragons",
    editorial: "Fantasy Realms",
    publicacion: 2022,
    paginas: 285,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Les Secrets du Royaume Perdu",
    editorial: "Editions Aventures",
    publicacion: 2019,
    paginas: 305,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Underwater World",
    editorial: "Oceanic Adventures",
    publicacion: 2021,
    paginas: 325,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Travesias por el Viejo Oeste",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 335,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Enquetes du Detective Williams",
    editorial: "Editions Mystere",
    publicacion: 2023,
    paginas: 295,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Secrets of Ancient Egypt",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 275,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de las Criaturas Magicas",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 315,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Voyages de l'Explorateur Solitaire",
    editorial: "Editions Aventure",
    publicacion: 2018,
    paginas: 255,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 285,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Arte de la Magia",
    editorial: "Magia y Hechiceria",
    publicacion: 2021,
    paginas: 295,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Fees du Monde",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 265,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Garden of Wonders",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 315,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas Misteriosos",
    editorial: "Aventuras Fantasticas",
    publicacion: 2018,
    paginas: 295,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de l'Ocean Inexplore",
    editorial: "Editions Sous-marines",
    publicacion: 2022,
    paginas: 285,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Haunted Forest",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 275,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en la Tierra de los Dragones Miticos",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 325,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres Enigmatiques",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 305,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Lost Civilization",
    editorial: "Ancient Mysteries",
    publicacion: 2022,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Grimorio de las Sombras",
    editorial: "Magia Oscura",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Aventures de l'Explorateur",
    editorial: "Editions Aventure",
    publicacion: 2018,
    paginas: 250,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Cursed Amulet",
    editorial: "Curse Breaker Publishing",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro Prohibido",
    editorial: "Magia Antigua",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Les Contes de Fees",
    editorial: "Contes Magiques",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Enchanted Forest",
    editorial: "Garden Publishing",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Tesoro de la Isla Perdida",
    editorial: "Aventuras Marinas",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Les Secrets de la Lune",
    editorial: "Editions Lunaire",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Witch's Curse",
    editorial: "Witchcraft Press",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Aventuras en el Mundo Subterraneo",
    editorial: "Subterranean Books",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Mysteres",
    editorial: "Chateau Editions",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  //   313 DATOS
  {
    titulo: "The Quest for the Lost Treasure",
    editorial: "Adventure Chronicles",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Misterio de la Mansion Encantada",
    editorial: "Libros de Misterio",
    publicacion: 2021,
    paginas: 275,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Ancient Legends and Myths",
    editorial: "Historical Myths",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Voyage to the Forgotten Realms",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Secrets of the Lost Kingdom",
    editorial: "Adventure Discoveries",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ghostly Shipwrecks",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Travesias en el Salvaje Oeste",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Detective's Investigations",
    editorial: "Mystery Editions",
    publicacion: 2023,
    paginas: 295,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ancient Civilizations",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de las Criaturas Miticas",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 315,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Adventures of the Lonely Explorer",
    editorial: "Adventure Editions",
    publicacion: 2018,
    paginas: 255,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 285,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Arte de la Magia Oscura",
    editorial: "Magia y Hechiceria",
    publicacion: 2021,
    paginas: 295,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Tales of World Fairytales",
    editorial: "Magical Tales",
    publicacion: 2019,
    paginas: 265,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Enchanted Garden of Wonders",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 315,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas Misteriosos",
    editorial: "Fantastic Adventures",
    publicacion: 2018,
    paginas: 295,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Secrets of the Unexplored Ocean",
    editorial: "Underwater Editions",
    publicacion: 2022,
    paginas: 285,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Haunted Forest",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 275,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Adventures in the Land of Mythical Dragons",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 325,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres Enigmatiques",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 305,
    idiomas: ["Frances"],
  },
  {
    titulo: "The Lost Civilization",
    editorial: "Ancient Mysteries",
    publicacion: 2022,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Grimorio de las Sombras",
    editorial: "Dark Magic",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Adventures of the Brave Explorer",
    editorial: "Adventure Journeys",
    publicacion: 2018,
    paginas: 260,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Cursed Amulet",
    editorial: "Curse Breaker Publishing",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro Prohibido",
    editorial: "Ancient Magic",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Fairy Tales",
    editorial: "Magical Tales",
    publicacion: 2019,
    paginas: 260,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Enchanted Forest",
    editorial: "Garden Publishing",
    publicacion: 2023,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Tesoro de la Isla Perdida",
    editorial: "Marine Adventures",
    publicacion: 2018,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Secrets of the Mysterious Moon",
    editorial: "Lunar Editions",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Witch's Curse",
    editorial: "Witchcraft Press",
    publicacion: 2020,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Adventures in the Subterranean World",
    editorial: "Subterranean Books",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Mysteres",
    editorial: "Chateau Editions",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Frances"],
  },
  //   345 DATOS
  {
    titulo: "The Legends of Camelot",
    editorial: "Arthurian Chronicles",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Secreto de la Montaña Sagrada",
    editorial: "Misterios Antiguos",
    publicacion: 2021,
    paginas: 275,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Lost Worlds and Forgotten Realms",
    editorial: "Historical Myths",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Voyage to the Enchanted Isles",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Secrets of the Ancient Empire",
    editorial: "Adventure Discoveries",
    publicacion: 2019,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ghost Ship of Haunted Seas",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Travesias en el Viejo Oeste",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Detective's Enigmas",
    editorial: "Mystery Editions",
    publicacion: 2023,
    paginas: 295,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Forgotten Civilizations",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Grimorio de los Magos",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 315,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Journeys of Adventurous Explorers",
    editorial: "Adventure Editions",
    publicacion: 2018,
    paginas: 255,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 285,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de las Hechiceras",
    editorial: "Magia y Hechiceria",
    publicacion: 2021,
    paginas: 295,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Tales of World Mythology",
    editorial: "Magical Tales",
    publicacion: 2019,
    paginas: 265,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Enchanted Gardens",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 315,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas Antiguos",
    editorial: "Fantastic Adventures",
    publicacion: 2018,
    paginas: 295,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Secrets of the Deep Ocean",
    editorial: "Underwater Editions",
    publicacion: 2022,
    paginas: 285,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Haunted Forest",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 275,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Adventures in the Land of Dragons",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 325,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres Enigmatiques",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 305,
    idiomas: ["Frances"],
  },
  // 365 DATOS
  {
    titulo: "The Quest for the Holy Grail",
    editorial: "Arthurian Chronicles",
    publicacion: 2022,
    paginas: 295,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Misterio de la Ciudad Perdida",
    editorial: "Misterios Antiguos",
    publicacion: 2021,
    paginas: 280,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Legends of Atlantis",
    editorial: "Historical Myths",
    publicacion: 2020,
    paginas: 315,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Voyage to the Mythical Lands",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 285,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Secrets of the Ancient Scrolls",
    editorial: "Adventure Discoveries",
    publicacion: 2019,
    paginas: 305,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ghostly Pirates",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 325,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Travesias en el Nuevo Mundo",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 335,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Detective's Chronicles",
    editorial: "Mystery Editions",
    publicacion: 2023,
    paginas: 295,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ancient Wonders",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 275,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Grimorio de los Hechiceros",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Journeys of Legendary Explorers",
    editorial: "Adventure Editions",
    publicacion: 2018,
    paginas: 260,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Curse of the Ancient Relics",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 290,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de las Magias Olvidadas",
    editorial: "Magia y Hechiceria",
    publicacion: 2021,
    paginas: 300,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Tales of Mythical Creatures",
    editorial: "Magical Tales",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Enchanted Gardens of Wonder",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas Antiguos II",
    editorial: "Fantastic Adventures",
    publicacion: 2018,
    paginas: 300,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Secrets of the Mysterious Abyss",
    editorial: "Underwater Editions",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Haunted Woods II",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Adventures in the Land of the Dragons II",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 330,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres Enigmatiques II",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 310,
    idiomas: ["Frances"],
  },
  //   385 DATOS
  {
    titulo: "The Quest for the Holy Grail",
    editorial: "Arthurian Chronicles",
    publicacion: 2022,
    paginas: 295,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Misterio de la Ciudad Perdida",
    editorial: "Misterios Antiguos",
    publicacion: 2021,
    paginas: 280,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Legends of Atlantis",
    editorial: "Historical Myths",
    publicacion: 2020,
    paginas: 315,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Voyage to the Mythical Lands",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 285,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Secrets of the Ancient Scrolls",
    editorial: "Adventure Discoveries",
    publicacion: 2019,
    paginas: 305,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ghostly Pirates",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 325,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Travesias en el Nuevo Mundo",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 335,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Detective's Chronicles",
    editorial: "Mystery Editions",
    publicacion: 2023,
    paginas: 295,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ancient Wonders",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 275,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Grimorio de los Hechiceros",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Journeys of Legendary Explorers",
    editorial: "Adventure Editions",
    publicacion: 2018,
    paginas: 260,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Curse of the Ancient Relics",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 290,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de las Magias Olvidadas",
    editorial: "Magia y Hechiceria",
    publicacion: 2021,
    paginas: 300,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Tales of Mythical Creatures",
    editorial: "Magical Tales",
    publicacion: 2019,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Enchanted Gardens of Wonder",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas Antiguos II",
    editorial: "Fantastic Adventures",
    publicacion: 2018,
    paginas: 300,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Secrets of the Mysterious Abyss",
    editorial: "Underwater Editions",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Haunted Woods II",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Adventures in the Land of the Dragons II",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 330,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres Enigmatiques II",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 310,
    idiomas: ["Frances"],
  },
  //   405 DATOS
  {
    titulo: "The Legendary Quests",
    editorial: "Arthurian Chronicles",
    publicacion: 2022,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Misterio de la Antigua Civilización",
    editorial: "Misterios Antiguos",
    publicacion: 2021,
    paginas: 285,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Myths and Legends of the World",
    editorial: "Historical Myths",
    publicacion: 2020,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Voyage to the Enchanted Forest",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 290,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Secrets of Lost Civilizations",
    editorial: "Adventure Discoveries",
    publicacion: 2019,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ghost Ship of Haunting Seas",
    editorial: "Maritime Mysteries",
    publicacion: 2021,
    paginas: 330,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Travesias en el Nuevo Continente",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 340,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Detective's Investigations",
    editorial: "Mystery Editions",
    publicacion: 2023,
    paginas: 305,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Wonders of Antiquity",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Magos Legendarios",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 325,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Voyages of Epic Explorers",
    editorial: "Adventure Editions",
    publicacion: 2018,
    paginas: 265,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Curse of the Enchanted Tombs",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 295,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de las Hechiceras Antiguas",
    editorial: "Magia y Hechiceria",
    publicacion: 2021,
    paginas: 305,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Tales of Mythical Beasts",
    editorial: "Magical Tales",
    publicacion: 2019,
    paginas: 275,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Enchanted Gardens of Marvels",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 325,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Antiguos Enigmas III",
    editorial: "Fantastic Adventures",
    publicacion: 2018,
    paginas: 305,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Secrets of the Profound Abyss",
    editorial: "Underwater Editions",
    publicacion: 2022,
    paginas: 295,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Haunted Woods III",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 285,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Adventures in the Land of the Dragons III",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 335,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres Enigmatiques III",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 315,
    idiomas: ["Frances"],
  },
  //   425 DATOS
  {
    titulo: "The Ancient Treasures of Egypt",
    editorial: "Pharaoh's Editions",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Secreto de los Caballeros Templarios",
    editorial: "Misterios Antiguos",
    publicacion: 2021,
    paginas: 290,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Legends of the Nordic Gods",
    editorial: "Mythical Tales",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Voyage to the Enchanted Isles",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Secrets of Ancient Temples",
    editorial: "Adventure Discoveries",
    publicacion: 2019,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ghostly Castles",
    editorial: "Mystical Mysteries",
    publicacion: 2021,
    paginas: 340,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Travesias en el Nuevo Horizonte",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 350,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Detective's Chronicles II",
    editorial: "Mystery Editions",
    publicacion: 2023,
    paginas: 315,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ancient Civilizations II",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 290,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de las Magias Antiguas II",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 330,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Voyages of Legendary Explorers II",
    editorial: "Adventure Editions",
    publicacion: 2018,
    paginas: 270,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs II",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Hechizos Antiguos II",
    editorial: "Magia y Hechiceria",
    publicacion: 2021,
    paginas: 310,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Tales of Mythical Creatures II",
    editorial: "Magical Tales",
    publicacion: 2019,
    paginas: 280,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Enchanted Gardens of Wonder II",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 330,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Enigmas Antiguos IV",
    editorial: "Fantastic Adventures",
    publicacion: 2018,
    paginas: 310,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Secrets of the Mysterious Abyss II",
    editorial: "Underwater Editions",
    publicacion: 2022,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Haunted Woods IV",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 290,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Adventures in the Land of the Dragons IV",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 340,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres Enigmatiques IV",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 320,
    idiomas: ["Frances"],
  },
  //   445 DATOS
  {
    titulo: "The Chronicles of Camelot",
    editorial: "Arthurian Chronicles",
    publicacion: 2022,
    paginas: 305,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Enigma de la Esfinge",
    editorial: "Misterios Antiguos",
    publicacion: 2021,
    paginas: 295,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Mythical Creatures of the World",
    editorial: "Mythical Tales",
    publicacion: 2020,
    paginas: 325,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Voyage to the Mysterious Lands",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 305,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Quest for Ancient Artifacts",
    editorial: "Adventure Discoveries",
    publicacion: 2019,
    paginas: 315,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ghostly Legends",
    editorial: "Mystical Mysteries",
    publicacion: 2021,
    paginas: 345,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Travesias en el Nuevo Horizonte II",
    editorial: "Western Adventures",
    publicacion: 2020,
    paginas: 355,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Detective's Chronicles III",
    editorial: "Mystery Editions",
    publicacion: 2023,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ancient Civilizations III",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 295,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de las Magias Antiguas III",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 335,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Voyages of Legendary Explorers III",
    editorial: "Adventure Editions",
    publicacion: 2018,
    paginas: 275,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs III",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 305,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Hechizos Antiguos III",
    editorial: "Magia y Hechiceria",
    publicacion: 2021,
    paginas: 315,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Tales of Mythical Creatures III",
    editorial: "Magical Tales",
    publicacion: 2019,
    paginas: 285,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Enchanted Gardens of Wonder III",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 335,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Antiguos Enigmas V",
    editorial: "Fantastic Adventures",
    publicacion: 2018,
    paginas: 315,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Secrets of the Mysterious Abyss III",
    editorial: "Underwater Editions",
    publicacion: 2022,
    paginas: 305,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Haunted Woods V",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 295,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Adventures in the Land of the Dragons V",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 345,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres Enigmatiques V",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 325,
    idiomas: ["Frances"],
  },
  // 465 DATOS
  {
    titulo: "The Lost City of Atlantis Revisited",
    editorial: "Ancient Mysteries",
    publicacion: 2022,
    paginas: 320,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Misterio del Tesoro Hundido",
    editorial: "Misterios del Mar",
    publicacion: 2021,
    paginas: 300,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Myths and Legends of Ancient Rome",
    editorial: "Mythical Tales",
    publicacion: 2020,
    paginas: 330,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Journey to the Enchanted Forests II",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Quest for Hidden Treasures II",
    editorial: "Adventure Discoveries",
    publicacion: 2019,
    paginas: 340,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ghostly Shipwrecks III",
    editorial: "Mystical Mysteries",
    publicacion: 2021,
    paginas: 350,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Travesias en el Desierto Profundo III",
    editorial: "Desert Adventures",
    publicacion: 2020,
    paginas: 360,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Detective's Chronicles VI",
    editorial: "Mystery Editions",
    publicacion: 2023,
    paginas: 330,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ancient Civilizations VI",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 325,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Hechizos Antiguos VI",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 340,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Voyages of Legendary Explorers VI",
    editorial: "Adventure Editions",
    publicacion: 2018,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs VI",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Encantamientos II",
    editorial: "Magia y Hechiceria",
    publicacion: 2021,
    paginas: 320,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Tales of Celtic Mythology II",
    editorial: "Magical Tales",
    publicacion: 2019,
    paginas: 290,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Enchanted Gardens of Wonder VI",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 340,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Laberinto de los Antiguos Enigmas VIII",
    editorial: "Fantastic Adventures",
    publicacion: 2018,
    paginas: 320,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Secrets of the Mysterious Abyss VI",
    editorial: "Underwater Editions",
    publicacion: 2022,
    paginas: 310,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Haunted Woods VIII",
    editorial: "Mystical Forest Publications",
    publicacion: 2020,
    paginas: 300,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Adventures in the Land of the Dragons VIII",
    editorial: "Dragon Tales",
    publicacion: 2021,
    paginas: 350,
    idiomas: ["Espanol"],
  },
  {
    titulo: "Le Chateau des Ombres Enigmatiques VIII",
    editorial: "Chateau Sombre",
    publicacion: 2019,
    paginas: 340,
    idiomas: ["Frances"],
  },
  //   485 DATOS
  {
    titulo: "The Chronicles of Camelot",
    editorial: "Medieval Tales",
    publicacion: 2022,
    paginas: 325,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Enigma de la Esfinge",
    editorial: "Misterios Antiguos",
    publicacion: 2021,
    paginas: 315,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "Legends of Greek Mythology",
    editorial: "Mythical Tales",
    publicacion: 2020,
    paginas: 335,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Expedition to the Lost City of Eldorado",
    editorial: "Adventure Classics",
    publicacion: 2022,
    paginas: 315,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Quest for the Crystal Skull",
    editorial: "Adventure Discoveries",
    publicacion: 2019,
    paginas: 345,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ghostly Shipwrecks IV",
    editorial: "Mystical Mysteries",
    publicacion: 2021,
    paginas: 355,
    idiomas: ["Ingles"],
  },
  {
    titulo: "Travesias en el Desierto Profundo IV",
    editorial: "Desert Adventures",
    publicacion: 2020,
    paginas: 365,
    idiomas: ["Espanol", "Ingles"],
  },
  {
    titulo: "The Detective's Chronicles VII",
    editorial: "Mystery Editions",
    publicacion: 2023,
    paginas: 340,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Ancient Civilizations VII",
    editorial: "Historical Discoveries",
    publicacion: 2019,
    paginas: 335,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Hechizos Antiguos VII",
    editorial: "Magia y Leyendas",
    publicacion: 2022,
    paginas: 345,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Voyages of Legendary Explorers VII",
    editorial: "Adventure Editions",
    publicacion: 2018,
    paginas: 305,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Curse of the Forbidden Tombs VII",
    editorial: "Ancient Archaeology",
    publicacion: 2020,
    paginas: 315,
    idiomas: ["Ingles"],
  },
  {
    titulo: "El Libro de los Encantamientos III",
    editorial: "Magia y Hechiceria",
    publicacion: 2021,
    paginas: 325,
    idiomas: ["Espanol"],
  },
  {
    titulo: "The Tales of Celtic Mythology III",
    editorial: "Magical Tales",
    publicacion: 2019,
    paginas: 295,
    idiomas: ["Ingles"],
  },
  {
    titulo: "The Enchanted Gardens of Wonder VII",
    editorial: "Garden of Wonders",
    publicacion: 2023,
    paginas: 345,
    idiomas: ["Ingles"],
  },
]);

//Find Biblioteca
// db.Biblioteca.find({publicacion:2020});

//Find One Biblioteca
// db.Biblioteca.findOne({publicacion:2021});

//Update One Biblioteca
// db.Biblioteca.updateOne({titulo:"El Viaje Eterno"},{$set:{editorial:"Libros Elsyum",paginas:222}});


//Update Many Biblioteca
// db.Biblioteca.updateMany({publicacion:2020},{$set:{paginas:260}});


//Delete One Biblioteca
// db.Biblioteca.deleteOne({publicacion:2018});



//Delete Many Biblioteca
//db.Biblioteca.deleteMany({editorial: "Libros de Misterio"});

//Drop collection Biblioteca
// db.Biblioteca.drop();

// //Drop DataBase Colegio
// db.dropDatabase("Biblioteca");



// OPERADORES DE CONSULTA

//encontrar en la biblioteca con la publicacion igual a 2022
// db.Biblioteca.find({publicacion:{$eq:2022}});

//encontrar en la biblioteca con la publicacion inferior a 2021
// db.Biblioteca.find({publicacion:{$lt:2021}});

//encontrar en la biblioteca con la publicacion inferior o igual a 2020
// db.Biblioteca.find({publicacion:{$lte:2020}});

//encontrar en la biblioteca con la publicacion mayor a 2018
// db.Biblioteca.find({publicacion:{$gt:2018}});

//encontrar en la biblioteca con la publicacion mayor o igual a 2019
// db.Biblioteca.find({publicacion:{$gte:2019}});

//encontrar en la biblioteca donde titulo no sea a viaje al futuro
//db.Biblioteca.find({titulo:{$ne:'Viaje al futuro'}});

//encontrar en la biblioteca donde editorial pertenece a 'Pharaon Editions'
//db.Biblioteca.find({editorial:{$in:['Pharaon Editions']}});

//encontrar en la biblioteca donde editorial no pertenece a 'Castle Books'
//db.Biblioteca.find({editorial:{$nin:['Castle Books']}});

//encontrar en la biblioteca donde editorial:'Editions Naturelles' y paginas:270
// db.Biblioteca.find({$and:[{editorial:'Editions Naturelles'},{paginas:270}]});

//encontrar en la biblioteca donde titulo se llamen El Misterio del Faro o The Ghostly Manor
// db.Biblioteca.find({$or:[{titulo:'El Misterio del Faro'},{titulo:'The Ghostly Manor'}]});

//encontrar en la biblioteca donde editorial no sea 'Historias Antiguas'
//db.Biblioteca.find({editorial:{$not:{$eq:'Historias Antiguas'}}});

// encontrar en la biblioteca con publicacion mayor 2020 y con idioma "Español"
// db.Biblioteca.find({ publicacion:{$gt:2020}, idiomas: "Espanol"},{"publicacion.$":1});

// consultar en la biblioteca con publicacion donde el valor del elemento 'idiomas' sea igual 'Ingles' y publicacion sea :2020
// db.Biblioteca.find({
//   $and: [{ publicacion: 2020 }, { idiomas: { $elemMatch: { $eq: "Ingles" } } }],
// });

//encontrar en la biblioteca los idiomas y devuelve 1 idioma
//db.Biblioteca.find({},{idiomas:{$slice:1}});

// //encontrar en la biblioteca todos los libros que el titulo tenga palabras relacionadas con 'The Curse of the Pharaohs'
// db.Biblioteca.createIndex({titulo:"text"})
// db.Biblioteca.find({$text:{$search:'The Curse of the Pharaohs'}});


//encontrar en la biblioteca todos los libros que editorial contenga 'Dragon'
//db.Biblioteca.find({editorial:{$regex:/Dragon/}});

//encontrar en la biblioteca todos los libros donde la suma de la publicacion y paginas sea menor o igual a 3.250
// db.Biblioteca.find({
//   $where: "this.publicacion + this.paginas <= 3250"
// });

//encontrar en la biblioteca todos los libros donde titulo exista
// db.Biblioteca.find({titulo:{$exists:true}});

//encontrar en la biblioteca todos los libros donde paginas sea de tipo 'string'
//db.Biblioteca.find({paginas:{$type:"string"}});

//encontrar en la biblioteca todos los libros donde publicacion sea de tipo 'int'
//db.Biblioteca.find({publicacion:{$type:"int"}});

//encontrar  en la biblioteca todos los libros contengan las materias:'Español','Ingles'
//db.Biblioteca.find({idiomas:{$all:["Espanol","Ingles"]}});


//encontrar  en la biblioteca todos los libros que el tamaño de idiomas sea 1
//db.Biblioteca.find({idiomas:{$size:1}});
